name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:

  sync:

    runs-on: ubuntu-latest
    env:
      ARCHITECTURE:
        -rk33xx
        -rk35xx
        -x86

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download files
      run: |
        for arch in "${{ env.ARCHITECTURE }}"
        do
          device: ${{ matrix.arch == 'rk33xx' && 'r5s' || matrix.arch == 'rk35xx' && 'h6xk' || matrix.arch == 'x86' && 'x86_64' }}

          curl -o ./$arch/feeds.conf https://fw0.koolcenter.com/iStoreOS/$device/feeds.conf
          curl -o ./$arch/.config https://fw0.koolcenter.com/iStoreOS/$device/config.buildinfo
          curl -o ./$arch/ota.footer.html https://fw0.koolcenter.com/iStoreOS/$device/ota.footer.html
        done

    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"
  
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.DEPLOY_TOKEN }}
