
name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create architecture directories
      run: |
        mkdir -p ./${{ matrix.ARCHITECTURE }}

    - name: Download files
      run: |
        curl -o ./rk33xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/r5s/feeds.conf
        curl -o ./rk33xx/.config https://fw0.koolcenter.com/iStoreOS/r5s/config.buildinfo
        curl -o ./rk33xx/ota.footer.html https://fw0.koolcenter.com/iStoreOS/r5s/ota.footer.html
        
        curl -o ./rk35xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/h6xk/feeds.conf
        curl -o ./rk35xx/.config https://fw0.koolcenter.com/iStoreOS/h6xk/config.buildinfo
        curl -o ./rk35xx/ota.footer.html https://fw0.koolcenter.com/iStoreOS/h6xk/ota.footer.html
        
        curl -o ./x86/feeds.conf https://fw0.koolcenter.com/iStoreOS/x86_64_efi/feeds.conf
        curl -o ./x86/.config https://fw0.koolcenter.com/iStoreOS/x86_64_efi/config.buildinfo
        curl -o ./x86/ota.footer.html https://fw0.koolcenter.com/iStoreOS/x86_64_efi/ota.footer.html

    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"
  
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.DEPLOY_TOKEN }}
