
name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:

  sync:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCHITECTURE: [rk33xx, rk35xx, x86]
      fail-fast: false

    env:
      device: ${{ matrix.ARCHITECTURE == 'rk33xx' && 'r5s' || matrix.ARCHITECTURE == 'rk35xx' && 'h6xk' || matrix.ARCHITECTURE == 'x86' && 'x86_64_efi' }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create architecture directories
      run: |
        mkdir -p ./${{ matrix.ARCHITECTURE }}

    - name: Download files
      run: |
        git pull
        curl -o ./${{ matrix.ARCHITECTURE }}/feeds.conf https://fw0.koolcenter.com/iStoreOS/${{ env.device }}/feeds.conf
        curl -o ./${{ matrix.ARCHITECTURE }}/.config https://fw0.koolcenter.com/iStoreOS/${{ env.device }}/config.buildinfo
        curl -o ./${{ matrix.ARCHITECTURE }}/ota.footer.html https://fw0.koolcenter.com/iStoreOS/${{ env.device }}/ota.footer.html

    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files for ${{ matrix.ARCHITECTURE }}"
  
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.DEPLOY_TOKEN }}
